### ISSUE TITLE
Small changes to layout of the contributors table

### ISSUE THREAD

**Issue by baileythegreen** [BobAnkh/add-contributors#31]
## Is your feature request related to a problem? Please describe

No, it's aesthetic.

## Description of the new feature/enhancement

An increase in the spacing between rows of the contributors. Currently, the name of a contributor on one row is practically on top of the image of the contributor directly below.

Also, wrapping the longer names might be nice.

## Proposed technical implementation details (optional)

Just insert a vertical space of a specified height between rows. I'm not sure about wrapping text in an html table; I've not done that.

## Additional context

Example from my repository, where I would like to have these aesthetic changes:

https://baileythegreen.github.io/glosario/contributors/

<img width="608" alt="Screen Shot 2020-12-05 at 22 58 33" src="https://user-images.githubusercontent.com/12277715/101267127-7df2b680-374d-11eb-9de3-c8873f338b3e.png">

**Comment by BobAnkh** [comment]
Thank you for your suggestions. I would really appreciate this kind of enhancement.

Would you like to take this issue?@baileythegreen
