### ISSUE TITLE
[enhancement] Exclude certain accounts from being listed in the contributors.

### ISSUE THREAD

**Issue by mmattbtw** [BobAnkh/add-contributors#46]
## Is your feature request related to a problem? Please describe

Yes, some bot accounts (like @renovate-bot and @codacy-badger) show up in the contributors. 

## Description of the new feature/enhancement

Add a parameter so you can pass in a list of users to ignore.

## Proposed technical implementation details (optional)
https://github.com/BobAnkh/add-contributors/blob/00b1222651ba056f977cf3ae40972812fdec4bbf/main.py#L81
After this line, you could simply just do
```py
if contributor['name'] not in IGNORED_CONTRIBUTORS:
```

**Comment by BobAnkh** [comment]
Really a good feature.

Would you like to take this? @mmattbtw

**Comment by BobAnkh** [comment]
@mmattbtw Hi, I have added this feature in [v0.2.0](https://github.com/BobAnkh/add-contributors/releases/tag/v0.2.0), you can try and test if this feature works as expected.

Again thank you for proposing this new feature.

**Comment by mmattbtw** [comment]
@BobAnkh didn't work for me on my repo, but I think #47 will fix it

**Comment by BobAnkh** [comment]
@mmattbtw I will see how you fix it in #47, to see if I can do this work.

**Comment by BobAnkh** [comment]
@mmattbtw Is this probably because that you specify an incorrect name for those accounts? I add debug log in the recent commits so that it will print all the contributors' names in the log.

Could you please see if you specify the correct name of those accounts?

**Comment by BobAnkh** [comment]
> @mmattbtw Is this probably because that you specify an incorrect name for those accounts? I add debug log in the recent commits so that it will print all the contributors' names in the log.
> 
> Could you please see if you specify the correct name of those accounts?

This log will be like that:

![image](https://user-images.githubusercontent.com/44333669/126022795-166bbf99-4dd2-41f2-b409-35629676ce07.png)

**Comment by mmattbtw** [comment]
Wait, are you supposed to add the display name? or the username

**Comment by BobAnkh** [comment]
Well here we use display name, for we are showing it in the contributors' list 🤣

**Comment by BobAnkh** [comment]
It seems that Github doesn't provide a good api to extract username? This is why I only support display name.

If you have a better idea on this issue, please tell me~

**Comment by mmattbtw** [comment]
Ah ok, I would just make sure you say something in the README.md that IGNORED_CONTRIBUTORS take display names and not usernames, other then that it looks good to me :]

**Comment by BobAnkh** [comment]
> Ah ok, I would just make sure you say something in the README.md that IGNORED_CONTRIBUTORS take display names and not usernames, other then that it looks good to me :]

@mmattbtw I update the readme file with a new NOTE.
