### ISSUE TITLE
[enhancement] Specify error message

### ISSUE THREAD

**Issue by BobAnkh** [BobAnkh/add-contributors#6]
## Is your feature request related to a problem? Please describe

If the user do not have something like `### Contributors` in the file where they want to add contributors, the program will throw a `IndexError: list index out of range` at [main.py#L130](https://github.com/BobAnkh/add-contributors/blob/c2cacfa6d74f9bf086de24d5327b7f80265e125a/main.py#L130)

## Description of the new feature/enhancement

The error message should be more clear to tell the user that they do not have `CONTRIBUTOR` section in their file.

## Proposed technical implementation details (optional)

I think there are two methods:

1. Add an if-statement to see if `length(text_str)` equals 2. If not, **stop** the program and tell the user what causes the problem.
2. Add a `try catch` block to catch `IndexError` and tell the users what causes the problem as well as stop the program.

**Comment by eddy-dot** [comment]
I'm tackling this one

**Comment by BobAnkh** [comment]
Thank you!
